// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_survivor_on_wheels = "CgkIhtTcqpkdEAIQEw"; // <GPGSID>
        public const string achievement_warmup_driver = "CgkIhtTcqpkdEAIQEQ"; // <GPGSID>
        public const string achievement_speedy = "CgkIhtTcqpkdEAIQAg"; // <GPGSID>
        public const string achievement_endurance_driver = "CgkIhtTcqpkdEAIQEA"; // <GPGSID>
        public const string achievement_warming_up = "CgkIhtTcqpkdEAIQCA"; // <GPGSID>
        public const string leaderboard_traffic_racer = "CgkIhtTcqpkdEAIQAA"; // <GPGSID>
        public const string achievement_out_of_control = "CgkIhtTcqpkdEAIQBA"; // <GPGSID>
        public const string achievement_ultimate_collector = "CgkIhtTcqpkdEAIQDg"; // <GPGSID>
        public const string achievement_iron_wheel = "CgkIhtTcqpkdEAIQEg"; // <GPGSID>
        public const string achievement_milestone_reached = "CgkIhtTcqpkdEAIQBg"; // <GPGSID>
        public const string achievement_rising_collector = "CgkIhtTcqpkdEAIQCw"; // <GPGSID>
        public const string achievement_god_of_the_road = "CgkIhtTcqpkdEAIQFg"; // <GPGSID>
        public const string achievement_you_got_the_courage = "CgkIhtTcqpkdEAIQAw"; // <GPGSID>
        public const string achievement_breaking_the_limit = "CgkIhtTcqpkdEAIQBQ"; // <GPGSID>
        public const string achievement_road_legend = "CgkIhtTcqpkdEAIQFA"; // <GPGSID>
        public const string achievement_serious_collector = "CgkIhtTcqpkdEAIQDA"; // <GPGSID>
        public const string achievement_score_master = "CgkIhtTcqpkdEAIQBw"; // <GPGSID>
        public const string achievement_first_step = "CgkIhtTcqpkdEAIQAQ"; // <GPGSID>
        public const string achievement_immortal_driver = "CgkIhtTcqpkdEAIQFQ"; // <GPGSID>
        public const string achievement_king_of_the_road = "CgkIhtTcqpkdEAIQCg"; // <GPGSID>
        public const string achievement_exclusive_ride = "CgkIhtTcqpkdEAIQDQ"; // <GPGSID>
        public const string achievement_driving_god = "CgkIhtTcqpkdEAIQCQ"; // <GPGSID>
        public const string achievement_familiar_road = "CgkIhtTcqpkdEAIQDw"; // <GPGSID>

}

